"""Lemma Function: Report Generator"""
from typing import Dict, Any, List
from datetime import datetime, timezone
import logging
logger = logging.getLogger("aegis.fn.report")

def generate_report(
    report_type: str,
    case: Dict[str, Any],
    evidence: List[Dict],
    timeline: List[Dict],
    hypotheses: List[Dict],
    risk_score: Dict,
    persons: List[Dict],
    generated_by: str = "report_agent",
) -> Dict[str, Any]:
    """
    Generate a forensic report in Markdown + structured JSON.
    Types: executive | investigator | court | evidence_index
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    generators = {
        "executive": _executive_report,
        "investigator": _investigator_report,
        "court": _court_report,
        "evidence_index": _evidence_index_report,
    }
    gen_fn = generators.get(report_type, _investigator_report)
    content = gen_fn(case, evidence, timeline, hypotheses, risk_score, persons, now)
    return {
        "report_type": report_type,
        "title": content["title"],
        "content_markdown": content["markdown"],
        "content_json": content["data"],
        "generated_at": now,
        "generated_by": generated_by,
        "status": "draft",  # requires approval before finalization
    }


def _executive_report(case, evidence, timeline, hypotheses, risk, persons, now) -> Dict:
    title = f"Executive Summary — {case.get('pod_key','CASE-?')}"
    top_hyp = sorted(hypotheses, key=lambda h: h.get("confidence_score",0), reverse=True)
    md = f"""# {title}
**Classification:** RESTRICTED · FOR AUTHORISED PERSONNEL ONLY
**Generated:** {now}  |  **Case:** {case.get('pod_key')}  |  **Status:** {case.get('status','active').upper()}

---

## Risk Assessment
- **Overall Risk Score:** {risk.get('overall_score', 'N/A')} / 100
- **Urgency Level:** {risk.get('urgency_level','N/A').upper()}

## Case Overview
**{case.get('name','?')}**  
District: {case.get('district','Unknown')} · Severity: {case.get('severity','medium').upper()}

## Key Findings
- Total evidence items: **{len(evidence)}**
- Timeline events: **{len(timeline)}**
- Persons of interest: **{len(persons)}**

## Leading Hypothesis
{"**" + top_hyp[0]['title'] + "**  " + chr(10) + top_hyp[0].get('description','') if top_hyp else "No hypotheses generated yet."}

## Recommended Actions
{chr(10).join(f"- {r}" for r in risk.get('recommendations', ['Continue investigation']))}

---
*This report is AI-assisted. All findings require human verification before action.*
"""
    return {"title": title, "markdown": md, "data": {"risk": risk, "hypothesis_count": len(hypotheses)}}


def _investigator_report(case, evidence, timeline, hypotheses, risk, persons, now) -> Dict:
    title = f"Investigator Report — {case.get('pod_key','CASE-?')}"
    md = f"""# {title}
**Generated:** {now} | **Case:** {case.get('pod_key')} | **FIR:** {case.get('fir_number','N/A')}

---

## Case Summary
- **Name:** {case.get('name')}
- **District:** {case.get('district','N/A')}
- **Severity:** {case.get('severity','medium').upper()}
- **Assigned Investigators:** {', '.join(case.get('investigators',[]) or ['Unassigned'])}

## Evidence Inventory ({len(evidence)} items)
{"".join(f"| {e.get('evidence_number','?')} | {e.get('name','?')} | {e.get('evidence_type','?')} | {e.get('priority_score',0):.0f} |{chr(10)}" for e in evidence[:20])}

## Timeline Summary
{chr(10).join(f"- **{ev.get('timestamp_iso','?')[:16]}** — {ev.get('title','?')}" for ev in timeline[:15])}

## Hypotheses
{chr(10).join(f"### H{h['hypothesis_number']}: {h['title']}{chr(10)}Confidence: {h.get('confidence_score',0):.0%}{chr(10)}{h.get('description','')}{chr(10)}" for h in hypotheses)}

## Risk Assessment
- Score: {risk.get('overall_score','N/A')} | Urgency: {risk.get('urgency_level','N/A')}
- Anomalies: {len(risk.get('anomalies',[]))}
- Inconsistencies: {len(risk.get('inconsistencies',[]))}

---
*AEGIS-OS AI-Assisted Report — Requires investigator sign-off before submission.*
"""
    return {"title": title, "markdown": md, "data": {"evidence_count": len(evidence), "timeline_count": len(timeline)}}


def _court_report(case, evidence, timeline, hypotheses, risk, persons, now) -> Dict:
    title = f"Court-Ready Summary — {case.get('pod_key','CASE-?')}"
    md = f"""# {title}
**Classification:** LEGAL PROCEEDINGS USE ONLY
**Date:** {now} | **Case Reference:** {case.get('pod_key')} | **FIR:** {case.get('fir_number','N/A')}

> **NOTICE:** This document is generated by an AI-assisted forensic platform. All findings are
> investigative in nature and do not constitute a determination of guilt. Human expert review
> and verification are mandatory before submission to any legal proceeding.

---

## Case Reference
**{case.get('name','?')}** · {case.get('district','?')} District

## Evidence Chain of Custody
{chr(10).join(f"- **{e.get('evidence_number','?')}** — {e.get('name','?')} | Hash: {e.get('file_hash','N/A')[:16]}..." for e in evidence[:15])}

## Expert Findings
{chr(10).join(f"- {h.get('title','?')} (Confidence: {h.get('confidence_score',0):.0%})" for h in hypotheses)}

## Data Integrity
All evidence files are SHA-256 verified. Chain of custody maintained throughout investigation.

---
*This report requires approval from lead investigator and legal review before court submission.*
"""
    return {"title": title, "markdown": md, "data": {"approved": False, "requires_legal_review": True}}


def _evidence_index_report(case, evidence, timeline, hypotheses, risk, persons, now) -> Dict:
    title = f"Evidence Index — {case.get('pod_key','CASE-?')}"
    rows = "\n".join([
        f"| {e.get('evidence_number','?')} | {e.get('name','?')} | {e.get('evidence_type','?')} | "
        f"{e.get('uploaded_at','?')[:10]} | {e.get('file_hash','N/A')[:16]}... |"
        for e in evidence
    ])
    md = f"""# {title}
**Generated:** {now} | Total: {len(evidence)} items

| # | Name | Type | Uploaded | Hash (SHA-256) |
|---|------|------|----------|---------------|
{rows}

---
*All evidence items verified. Full hashes available in raw JSON export.*
"""
    return {"title": title, "markdown": md, "data": {"evidence": [e.get("id") for e in evidence]}}
